[project]
name = "chirper"
version = "0.1.0"
description = "The is a 'Twitter' like app created for my app development class."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=5.1.6",
    "django-allauth>=65.4.0",
    "pillow>=11.1.0",
]
