# Generated by Django 5.1.6 on 2025-02-07 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chirper_app', '0003_reply_alter_chirp_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chirp',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reply',
            name='chirp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='Chirper_app.chirp'),
            preserve_default=False,
        ),
    ]
