# Generated by Django 5.1.6 on 2025-02-07 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chirper_app', '0004_chirp_like_count_reply_chirp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
