# Generated by Django 5.1.6 on 2025-02-09 01:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chirper_app', '0005_alter_reply_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='is_chirp_reply',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reply',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reply',
            name='parent_reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='Chirper_app.reply'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='chirp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='Chirper_app.chirp'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
